const {chromium,firefox,webkit}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.TEST_BASE_URL||'http://localhost:8000';
const engine=process.env.QA_ENGINE||'chrome',out=(process.env.QA_OUTPUT||'.test-results/review')+'/'+engine;
fs.mkdirSync(out,{recursive:true});
const report={engine,checks:[],errors:[]};
const check=label=>{report.checks.push(label);console.log('PASS',label)};
const id='demo-ibarra-respuestas';
const note='Completar evidencia del taller.\nAdjuntar matriz de aportes. <b>Revisión MIT</b>';
const read=p=>p.evaluate(id=>{const key=Object.keys(localStorage).find(k=>k.endsWith(':records'));return JSON.parse(localStorage.getItem(key)).records.find(r=>r.id===id)},id);
const open=async p=>{await p.locator(`[data-open-record="${id}"]`).click();await p.locator('#mit-review-comment').waitFor()};
const close=async p=>{await p.locator('#modal [data-close]').click()};
let browser;
(async()=>{try{
 browser=await (engine==='firefox'?firefox:engine==='webkit'?webkit:chromium).launch({headless:true,...(['chrome','edge'].includes(engine)?{channel:engine==='edge'?'msedge':'chrome'}:{})});
 report.version=browser.version();
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{window.prompt=()=>{throw new Error('No debe usarse prompt para observar registros')}});
 const mit=await context.newPage(),gadm=await context.newPage();
 for(const p of [mit,gadm]){p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())})}
 await mit.goto(base+'/plataforma/?role=mit');await mit.locator('#filter-canton').selectOption('ibarra');
 await gadm.goto(base+'/plataforma/?role=gadm&canton=ibarra');await gadm.locator('[data-tab="records"]').click();
 await open(mit);await mit.locator('#observe-record').click();await mit.locator('#mit-review-note').fill('   ');await mit.locator('#save-review').click();
 assert.match(await mit.locator('.review-error').innerText(),/motivo/);assert.equal((await read(mit)).estado,'enviado');
 await mit.locator('#mit-review-note').fill(note);await mit.locator('#cancel-review').click();assert.equal((await read(mit)).estado,'enviado');
 await mit.locator('#observe-record').click();assert.equal(await mit.locator('#mit-review-note').inputValue(),note);
 check('Formulario integrado, validación de texto vacío y cancelación sin cambios');
 await mit.locator('#save-review').click();await mit.locator('#mit-review-form').waitFor({state:'hidden'});
 assert.equal(await mit.locator('#mit-review-comment').innerText(),note);assert.equal(await mit.locator('#mit-review-comment b').count(),0);
 assert.equal((await read(mit)).validacion,note);await mit.reload();await mit.locator('#filter-canton').selectOption('ibarra');await open(mit);
 assert.equal(await mit.locator('#mit-review-comment').innerText(),note);await close(mit);
 check('Observación guardada, visible inmediatamente y persistente tras recargar');
 await open(gadm);assert.equal(await gadm.locator('#mit-review-comment').innerText(),note);
 await gadm.locator('#edit-record').click();assert.equal(await gadm.locator('#mit-review-comment').innerText(),note);
 await gadm.locator('#r-observacion').fill('Respuesta municipal: se completa la evidencia.');await gadm.locator('button[value="borrador"]').click();await gadm.locator('#modal').waitFor({state:'hidden'});
 assert.equal((await read(gadm)).validacion,note);await open(gadm);await gadm.locator('#send-record').click();await gadm.locator('#modal').waitFor({state:'hidden'});
 assert.equal((await read(gadm)).validacion,note);await open(mit);assert.equal(await mit.locator('#mit-review-comment').innerText(),note);
 check('Comentario visible al GADM y conservado al corregir y reenviar');
 await mit.locator('#observe-record').click();await mit.locator('#mit-review-note').fill('Precisar el período de la matriz.');await mit.locator('#save-review').click();await mit.locator('#mit-review-form').waitFor({state:'hidden'});
 assert.equal(await mit.locator('#mit-review-comment').innerText(),'Precisar el período de la matriz.');
 await mit.getByText('Comentarios anteriores (1)',{exact:true}).click();assert((await mit.locator('.mit-review-summary').innerText()).includes(note));
 if(engine==='chrome')await mit.screenshot({path:out+'/review-saved.png'});
 check('Nuevas observaciones conservan los comentarios anteriores en la ficha');
 await mit.locator('#observe-record').click();await mit.locator('#mit-review-note').fill('Comentario pendiente de guardado.');
 await mit.evaluate(()=>{window.restoreStorage=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Prueba de cuota','QuotaExceededError')}});
 await mit.locator('#save-review').click();await mit.waitForFunction(()=>document.querySelector('.review-error')?.textContent.trim());assert.match(await mit.locator('.review-error').innerText(),/No se pudo guardar/);assert.equal(await mit.locator('#mit-review-note').inputValue(),'Comentario pendiente de guardado.');
 assert.equal((await read(mit)).validacion,'Precisar el período de la matriz.');await mit.evaluate(()=>{Storage.prototype.setItem=window.restoreStorage;delete window.restoreStorage});
 check('Un error de almacenamiento conserva el texto y no anuncia un guardado');
 await open(gadm);await gadm.locator('#send-record').click();await gadm.locator('#modal').waitFor({state:'hidden'});
 await mit.locator('#save-review').click();await mit.waitForFunction(()=>document.querySelector('.review-error')?.textContent.trim());assert.match(await mit.locator('.review-error').innerText(),/cambió/);assert.equal(await mit.locator('#mit-review-note').inputValue(),'Comentario pendiente de guardado.');
 check('Una revisión obsoleta no sobrescribe datos ni pierde el texto escrito');
 await mit.setViewportSize({width:390,height:844});assert(await mit.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));
 if(engine==='chrome'){await mit.locator('#mit-review-note').scrollIntoViewIfNeeded();await mit.screenshot({path:out+'/review-mobile.png'})}
 await close(mit);await open(mit);await mit.locator('#validate-record').click();await mit.locator('#modal').waitFor({state:'hidden'});await open(mit);
 assert.equal((await read(mit)).estado,'validado');await mit.getByText('Comentarios anteriores (2)',{exact:true}).click();assert((await mit.locator('.mit-review-summary').innerText()).includes(note));
 check('Formulario móvil sin desbordamiento y observaciones conservadas tras validar');
 assert.deepEqual(report.errors,[]);check('Consola sin errores');await context.close();
}catch(e){report.failure=e.stack;console.error(e.stack);process.exitCode=1}finally{await browser?.close();fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2))}})();
