import {STATES} from './model.js';
export const $=(s,root=document)=>root.querySelector(s);
export const $$=(s,root=document)=>[...root.querySelectorAll(s)];
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const pretty=s=>String(s??'').replaceAll('-',' ');
export const no='No definida en los documentos';
export const date=s=>s?new Date(s).toLocaleString('es-EC',{dateStyle:'medium',timeStyle:'short'}):'Sin actualización';
export const badge=n=>`<span class="badge ${n.estadoMedicion===Object.keys(STATES)[0]?'teal':n.estadoMedicion===Object.keys(STATES)[1]?'amber':'slate'}">${esc(STATES[n.estadoMedicion]?.short||n.estadoMedicion)}</span>`;
export function options(items,value='',blank='Todos'){return (blank!==null?`<option value="">${esc(blank)}</option>`:'')+items.map(i=>`<option value="${esc(i.id)}" ${value===i.id?'selected':''}>${esc(i.nombre)}</option>`).join('')}
export function notify(message,error=false){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.setAttribute('role','status');document.body.append(el)}el.textContent=message;el.className=error?'error':'';el.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.hidden=true,error?12000:6000)}
export function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function modal(title,html){let d=$('#modal');if(d)d.remove();d=document.createElement('dialog');d.id='modal';d.innerHTML=`<header class="dialog-head"><h2>${esc(title)}</h2><button class="icon" data-close aria-label="Cerrar ventana">✕</button></header><div class="dialog-body">${html}</div>`;document.body.append(d);$('[data-close]',d).onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.showModal();return d}
export function sourceText(n){return `${n.paginaGuia?`Guía p. ${n.paginaGuia} (PDF ${n.paginaGuia+3})`:'Sin página de Guía'} · ${n.paginaTdR?`TdR p. ${n.paginaTdR}`:'Sin página de TdR'}`}
export function nodeDetails(n,c){const label=(ids)=>ids.map(id=>c.nodes.find(x=>x.id===id)?.nombre||id).join(' · ')||'Transversal / sin asignación';const rows=[['Nivel',n.nivel],['Categoría',n.categoria],['Claves',label(n.claveECP)],['Ejes',label(n.ejeECP)],['Naturaleza',pretty(n.naturalezaMedicion)],['Fuente de medición',n.fuenteMedicion||no],['Unidad documental',n.unidad||no],['Fórmula documental',n.formula||no],['Periodicidad documental',n.periodicidad||no],['Referencia',sourceText(n)],['Documentos',n.fuenteDocumento.join(' · ')||'Sin referencia'],['Notas',n.notas||'Sin notas']];return `${badge(n)}<p>${esc(n.descripcion)}</p><dl class="facts">${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${n.captura?`<p class="notice">Captura demo: ${esc(n.captura.tipo==='number'?n.captura.unidadDemo:'observación descriptiva')}. ${esc(n.captura.convencion||'Convención de demostración; no es metodología aprobada.')}</p>`:''}`}
export function fileInput(onFile){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{if(i.files[0])await onFile(await i.files[0].text())}catch(e){notify(e.message,true)}};i.click()}
export function registerReadTool(name,description,execute){try{document.modelContext?.registerTool({name,description,inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(input&&Object.keys(input).length)throw new Error('No se aceptan argumentos.');return execute()}})}catch{}}
